### ISSUE TITLE
Long titled choice with the list prompt makes it jump up on every scroll

### ISSUE THREAD

**Issue by sindresorhus** [SBoudrias/Inquirer.js#261]
## Problem

If you use a long title in one of the choices in the `list` prompt it makes the list jump one lin up for every scroll and creates a lot of artifacts and ghost lines.

<img width="1430" alt="screen shot 2015-07-26 at 22 01 32" src="https://cloud.githubusercontent.com/assets/170270/8895657/e8ea55e4-33e1-11e5-8e4c-0ce251246f99.png">

## Testcase

```js
'use strict';
var inquirer = require('inquirer');

inquirer.prompt([
  {
    type: 'list',
    name: 'foo',
    message: 'foo',
    choices: [
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.',
      'Make a reservation'
    ]
  }
]);
```

-

Can also be reproduced with `yo` master: `yo` => `Install a generator` => `angular` => [Enter]

**Comment by SBoudrias** [comment]
It's working fine for me with the latest inquirer 0.9 release. I believe yo is still on 0.8. - So this rendering bug shouldn't be an issue with latest version.

That being said, maybe some improvements could be done for long choices as if it spawn on a multiple lines it shows up pretty abruptly. My concern here is that if we start cutting the choice text to fit the screen scroll state, then we might end up with more edge case. What if the question is longer than the maximum number of line? Can we assure the choice is readable in its totally when it's selected? I don't really have an answer for these currently - and I'm not sure pursuing a fix here is currently worthwhile.

**Comment by SBoudrias** [comment]
Ah, actually this bug only show up on terminal (I was testing with iterm). Will investigate.

**Comment by sindresorhus** [comment]
Oh yeah, I should have been more specific. Terminal.app, Node 0.12.7, Inquirer 0.9.0.

> My concern here is that if we start cutting the choice text to fit the screen scroll state, then we might end up with more edge case.

I might be misunderstanding this, but I don't want Inquirer to truncate the question.

**Comment by SBoudrias** [comment]
Investigated this tonight, I have a feeling the issue is when we reset the cursor to the left position, we send it too far and it silently goes up a line in Windows and Terminal, but not in iterm.

**Comment by sixertoy** [comment]
Hey :)
Should i confirm this issue also happens with a too long message value ?
On windows

**Comment by SBoudrias** [comment]
Sorry this is taking forever. Tried to figure out the inconsistencies for a while now, and I'm now pretty sure it's because when cleaning a line, Terminal will clean a prompt line with a wrapping answer, while iTerm only clean the current line.

I'm still a bit unsure of how I'll handle the inconsistency (and I also need to confirm the behavior on Windows), but now that I know the cause a fix should be coming soon.

**Comment by doapp-ryanp** [comment]
Can confirm this occurs on iTerm2 v 2.1.1 as well, and on previous 0.8.5 too (and .7).

FWIW we would like to use this in our new [JAWS](https://github.com/jaws-stack/JAWS) project that has quite a bit of visibility.  While no other tool is as good as yours, this issue is a big enough problem where we will are debating writing our own.

Do you have any rough eta? we are targeting release of JAWS 1.0 beta this thursday 9/10 and would really like to use this module.

**Comment by SBoudrias** [comment]
Can't reproduce on iterm v2.1.1, are you sure you tested latest version?

@doapp-ryanp FWIW, if you're debating writing your own, just send a PR fixing this bug and we'll merge it. That would be easier than rolling up your own solution.

**Comment by doapp-ryanp** [comment]
inquirer@0.9.0. Check out this screencast: https://dl.dropboxusercontent.com/u/1374786/inquirer.mov

I was hoping you would be able to fix since it sounds like you already had a fix coming soon, and to be honest node cli i/o is outside of my wheelhouse, so it would take me a long time diagnose and fix.

**Comment by ac360** [comment]
Inquirer is an incredible, wonderful tool and we really want to use it.  But, I'm also having similar issues rendering prompts in plain Mac Terminal using v0.9 and previous versions.

![inquirer_bugs](https://cloud.githubusercontent.com/assets/2752551/9722035/ac81aa36-555a-11e5-80a9-6375b52ab0f3.png)

**Comment by SBoudrias** [comment]
@ac360 @doapp-ryanp I know the cause, but the issue is a bit tricky to fix as it impact multiple kind of prompts who don't have the same requirements, so it need to be as transparent as possible. It'll take me a little while to fix it correctly.

That being said, Inquirer only struggle with automatic line returns because they're not handle in a consistent manner by all the prompts out there. If you manually set `\n` in your prompts/list choices, it'll work just fine. You can check `process.stdin.column` to know the size of your user window.

**Comment by SBoudrias** [comment]
FWIW not got a fix for OSx on master. But that's breaking on windows.

There's also some edge cases failures on OSx with the input prompt, but that seems fairly minor.

**Comment by SBoudrias** [comment]
I believe this is fixed on the latest version. Would someone mind testing it?

**Comment by abramdemski** [comment]
I am still having this problem on Mac, with this project: https://github.com/dranorter/metaprompt_command

**Comment by SBoudrias** [comment]
@abramdemski I think you should check with the maintainer of vorpal.
